#!/usr/bin/env bash
# install and configure Nginx on port 80

sudo apt-get update -y
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo service nginx restart
