#!/usr/bin/env bash
# install and configure Nginx on port 80

sudo apt-get update -y
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee file /var/www/html/index.nginx-debian.html
sudo service nginx restart
