#!/usr/bin/env bash
# Do some magic

if [ "${1}" == "restart" ]
then
  pkill -f "bash ./manage_my_process"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process restarted"
elif [ "${1}" == "stop" ]
then
  pkill -f "bash ./manage_my_process"
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"
elif [ "${1}" == "start" ]
then
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
