#!/usr/bin/env bash
# Do some magic

case "$1" in
  restart)
    pkill -f "bash ./manage_my_process"
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  stop)
    pkill -f "bash ./manage_my_process"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  start)
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
