#!/usr/bin/env bash
# You know the fizzbuzz drill

for ((idx = 1; idx < 101; idx++)); do
    if ((idx % 5 == 0 && idx % 3 == 0))
    then
        echo "FizzBuzz";
    elif ((idx % 5 == 0))
    then
        echo "Buzz";
    elif ((idx % 3 == 0))
    then
        echo "Fizz";
    else echo "$idx";
    fi
done
